# Generated by Django 2.2.1 on 2019-05-27 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterScraper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='date_collected',
            field=models.DateTimeField(),
        ),
    ]
