# Generated by Django 2.2.1 on 2019-05-28 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitterScraper', '0002_auto_20190527_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='sentiment_score',
            field=models.DecimalField(decimal_places=1, max_digits=5, null=True),
        ),
    ]
